import Head from 'next/head'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Academia Supapo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/IconLogo.svg" />
      </Head>
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
