import Head from 'next/head'
import '../styles/globals.css'
import 'tailwindcss/tailwind.css';
import { AuthProvider } from '../context/AuthContext';

function MyApp({ Component, pageProps }) {
  return (
    <AuthProvider>
      <Head>
        <title>Academia Supapo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/IconLogo.svg" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#082032" />
      </Head>
      <Component {...pageProps} />
    </AuthProvider>
  )
}

export default MyApp
